/**
 * Documented public endpoints, per docs.robinhood.com/chain/connecting.
 *
 * Rate limited and stated to be unsuitable for production, so they serve as the last-resort entry
 * in the app's transport list rather than the preferred one - see `src/lib/rpcEndpoints.ts` for the
 * ordering policy - and as the ONLY entry the wallet is ever offered (`src/config/chain.ts`).
 *
 * Kept in a module of its own, free of viem and of `import.meta.env`, because the production
 * Content-Security-Policy has to name every origin the app may open a connection to, and that
 * policy is generated by `build/securityHeaders.ts` in the Node process that runs the build. A
 * second copy of these hostnames in the header generator would be a number with no way to fail:
 * it would go stale the day an endpoint moves, and the symptom would be the app silently unable to
 * reach its own fallback.
 */
export const PUBLIC_RPC_BY_CHAIN: Record<number, string> = {
  4663: 'https://rpc.mainnet.chain.robinhood.com',
  46630: 'https://rpc.testnet.chain.robinhood.com',
}

/**
 * The chain a build targets, from a raw `VITE_CHAIN_ID`.
 *
 * Anything that is not exactly 4663 selects the testnet, which is the app's long-standing
 * behaviour and covers a blank, absent or malformed value without a separate branch for each.
 *
 * Shared with the build for the same reason as the map above: `build/securityHeaders.ts` has to
 * pick the same chain the app will pick, and a CSP that named the other chain's endpoint would
 * block the app's last-resort RPC fallback precisely when it was needed.
 */
export const activeChainIdFrom = (raw: string | undefined): number =>
  Number(raw ?? 46630) === 4663 ? 4663 : 46630
