/**
 * Where the app reads indexed data from, given a raw `VITE_SUBGRAPH_URL`.
 *
 * The default is the self-hosted stack in `subgraph/docker`: deployed as `octopus/octopus`, so the
 * path carries both segments, and graph-node's port 8000 is remapped to host 8100 because 8000
 * collides with other local services.
 *
 * ⚠️ Extracted into a module of its own for the same reason as `./publicRpc`, and after the same
 * defect was found in review: the production Content-Security-Policy has to name every origin the
 * app may connect to, and it is generated by `build/securityHeaders.ts` in the Node process running
 * the build. That generator originally read `VITE_SUBGRAPH_URL` raw, so with the variable UNSET the
 * app fell back to `localhost:8100` while the CSP named nothing - and a blocked `fetch` renders as
 * an empty panel, not as an error, which is indistinguishable from "nobody has traded".
 *
 * A default that only one of the two knows about is a number with no way to fail. Both read this.
 */
export const DEFAULT_SUBGRAPH_URL = 'http://localhost:8100/subgraphs/name/octopus/octopus'

/**
 * Resolve the subgraph endpoint.
 *
 * `||` rather than `??`, deliberately and matching the app's long-standing behaviour: an empty
 * string is a variable somebody blanked, not a request to fetch from the empty URL.
 */
export const subgraphUrlFrom = (raw: string | undefined): string => raw || DEFAULT_SUBGRAPH_URL
