// Minimal typed ABI for DevVesting (#35) - only the members the UI touches.
// Full ABI lives in ../../subgraph/abis/DevVesting.json (generated by forge).
//
// ⚠️ The vault's address is read from `LaunchpadFactory.devVesting()`, never from an env var: it is
// deployed by the factory's own constructor, so asking the factory removes a whole class of
// misconfiguration (ADR-0003).
//
// `vestedAmount` is deliberately ABSENT: the vested figure is computed client-side so it can TICK
// between renders - see `lib/vesting.ts` for why no stored figure would be honest.
export const devVestingAbi = [
  // The whole grant, frozen at creation and never mutable except for `claimed`.
  //
  // ⚠️ Read from the chain rather than from the indexer, for the same Stage-2 reason as the lock
  // terms: an indexer outage would otherwise remove the creator's own claim button from the page,
  // even though `claim` is a plain chain call that has nothing to do with the read model. It also
  // makes `claimed` exact rather than as-of-the-last-indexed-event.
  //
  // ⚠️ **The field order is `(creator, duration, total, claimed)` and it is NOT the order the struct
  // reads in the source.** `VestingGrant` packs `creator` and `duration` into slot 0 and the two
  // `uint128` amounts into slot 1. Getting this wrong decodes silently into plausible nonsense -
  // a duration read as a token balance is still a number.
  {
    type: 'function',
    name: 'grantOf',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'creator', type: 'address' },
          { name: 'duration', type: 'uint64' },
          { name: 'total', type: 'uint128' },
          { name: 'claimed', type: 'uint128' },
        ],
      },
    ],
  },
  // The authoritative claimable figure, and the one the claim button acts on.
  //
  // ⚠️ Read from the chain even though `lib/vesting.ts` can compute it, and the difference matters:
  // the client figure is what has VESTED by the browser's clock, while this is what `claim` will
  // actually pay at the head block. A button offering a number the transaction then refuses is the
  // failure being avoided.
  {
    type: 'function',
    name: 'claimable',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  // ⚠️ `claim` takes NO recipient and never will: it pays `grant.creator`, frozen at creation. So the
  // connected wallet cannot change WHERE the tokens go - anyone may push a creator's claim and it
  // still lands with the creator. The button is nonetheless shown only to the creator, because for
  // anybody else it is a gas cost that benefits a stranger with no explanation on screen.
  {
    type: 'function',
    name: 'claim',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [{ name: 'amount', type: 'uint256' }],
  },
] as const
