// Minimal typed ABI for GraduationManager - only the member the UI touches.
// Full ABI lives in ../../subgraph/abis/GraduationManager.json (generated by forge).
//
// ⚠️ The manager's address is read from `LaunchpadFactory.graduationManager()`, never from an env
// var: it is deployed by the factory's own constructor, so asking the factory removes a whole class
// of misconfiguration (ADR-0003).
export const graduationManagerAbi = [
  // The moment a launch graduated, and the origin of every vesting schedule (ADR-0007).
  //
  // ⚠️ **Zero means "has not graduated", not "graduated at the epoch".** It is a `uint64` timestamp
  // and it was a `bool` until #35, so any code or comment treating it as a flag is reading a
  // superseded interface.
  //
  // ⚠️ Read from the chain rather than from the indexed row's `graduatedAtTimestamp`. The vesting
  // card needs it to place a schedule on a timeline, and sourcing it from the read model meant an
  // indexer outage rendered a graduated launch as "if this curve never graduates, the creator never
  // receives any of it" - a positive falsehood about a schedule that is already running, on the one
  // panel that exists to disclose it. The same Stage-2 reason the lock terms and the grant are read
  // directly: see `hooks/useLaunchTerms.ts`.
  {
    type: 'function',
    name: 'graduatedAt',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint64' }],
  },
] as const
