// Minimal typed ABI for LaunchpadFactory — only the members the UI touches.
// Full ABI lives in ../../subgraph/abis/LaunchpadFactory.json (generated by forge).
export const launchpadFactoryAbi = [
  {
    type: 'function',
    name: 'createLaunch',
    stateMutability: 'payable',
    // #33: the creator's choices moved behind one `LaunchParams` struct, so future launch options
    // (the dev allocation in #34) can be added without another signature break. Solidity encodes a
    // calldata struct as a tuple, and viem takes it as a single object argument.
    inputs: [
      {
        name: 'p',
        type: 'tuple',
        components: [
          { name: 'name', type: 'string' },
          { name: 'symbol', type: 'string' },
          // Permanent, set once at creation - the contract has no setter. See CreatePage.
          { name: 'metadataURI', type: 'string' },
          // Lock the graduation LP forever instead of the default 1 year. Terminal: it can never be
          // walked back. Surfaced on the create form in #37.
          { name: 'permanentLock', type: 'bool' },
          // #34: the creator's free allocation, in bps of the CURVE SUPPLY constant (not of this
          // launch's carved allocation), 0 to `maxDevAllocationBps`. Carved out of the curve
          // allocation and vested linearly from graduation (#35). Surfaced on the create form in #37.
          { name: 'devAllocationBps', type: 'uint16' },
        ],
      },
    ],
    outputs: [{ name: 'token', type: 'address' }],
  },
  {
    type: 'function',
    name: 'creationFee',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'launchCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'curveOf',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'creatorOf',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'address' }],
  },
  // Immutable. The launchpad names its own V3 factory, so the graduated-pool address is reachable
  // from the launchpad address alone (Stage 2) — one configured address, no second env var to drift.
  {
    type: 'function',
    name: 'v3Factory',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  // --- the four owner-tunable launch terms the create form quotes back (#37) ---
  //
  // ⚠️ **Read, never hardcoded.** All four are owner-tunable and future-only, and the whole point of
  // that design is that testnet feedback retunes the platform with a transaction. A form carrying
  // `500` or `365 days` as a literal turns every retune into a frontend deploy, and - worse - keeps
  // quoting the old terms to creators in the window before that deploy lands.
  {
    type: 'function',
    name: 'maxDevAllocationBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'defaultLockDuration',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
  },
  {
    type: 'function',
    name: 'vestingDuration',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
  },
  {
    type: 'function',
    name: 'creatorFeeBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint16' }],
  },
  // The curve-supply constant the dev allocation is a share OF. `devAllocationBps` is bps of this,
  // not of the launch's own carved allocation, so the token figure the form previews must divide by
  // this one. Immutable.
  {
    type: 'function',
    name: 'CURVE_SUPPLY',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  // --- this launch's own FROZEN terms, read per token (#37) ---
  //
  // ⚠️ Read from the chain rather than only from the indexer, and that is a Stage-2 decision. Both
  // are frozen at `createLaunch` and neither can ever change, so the indexer adds nothing but a
  // dependency - and during an indexer outage the lock panel would otherwise disappear entirely
  // from the page a buyer reads to find out whether the liquidity is locked at all.
  {
    type: 'function',
    name: 'lockConfigOf',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    // A public mapping over a struct flattens its members into separate return values.
    outputs: [
      { name: 'lockDuration', type: 'uint64' },
      { name: 'creatorFeeBps', type: 'uint16' },
      { name: 'permanent', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'devAllocationOf',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  // Immutable addresses of the three periphery contracts the token page reads. Taken from the
  // factory rather than from env vars, per ADR-0003: the launchpad is the root of identity, and all
  // three are deployed by its own constructor, so there is no configuration here that could drift
  // out of step with the factory the rest of the app is pointed at.
  {
    type: 'function',
    name: 'devVesting',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'lpLock',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'graduationManager',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'event',
    name: 'LaunchCreated',
    anonymous: false,
    inputs: [
      { name: 'token', type: 'address', indexed: true },
      { name: 'curve', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'symbol', type: 'string', indexed: false },
      { name: 'metadataURI', type: 'string', indexed: false },
      // The curve params frozen into this launch. Emitted so the UI can show the opening price and
      // the anti-snipe cap without an eth_call — which the pruned RPC refuses on historical blocks.
      { name: 'virtualEthReserve', type: 'uint256', indexed: false },
      { name: 'virtualTokenReserve', type: 'uint256', indexed: false },
      { name: 'curveTokenAllocation', type: 'uint256', indexed: false },
      { name: 'tradeFeeBps', type: 'uint16', indexed: false },
      { name: 'maxBuyPerWallet', type: 'uint256', indexed: false },
      { name: 'antiSnipeThreshold', type: 'uint256', indexed: false },
    ],
  },
] as const
