// Minimal typed ABI for LaunchpadFactory — only the members the UI touches.
// Full ABI lives in ../../subgraph/abis/LaunchpadFactory.json (generated by forge).
export const launchpadFactoryAbi = [
  {
    type: 'function',
    name: 'createLaunch',
    stateMutability: 'payable',
    // #33: the creator's choices moved behind one `LaunchParams` struct, so future launch options
    // (the dev allocation in #34) can be added without another signature break. Solidity encodes a
    // calldata struct as a tuple, and viem takes it as a single object argument.
    inputs: [
      {
        name: 'p',
        type: 'tuple',
        components: [
          { name: 'name', type: 'string' },
          { name: 'symbol', type: 'string' },
          // Permanent, set once at creation - the contract has no setter. See CreatePage.
          { name: 'metadataURI', type: 'string' },
          // Lock the graduation LP forever instead of the default 1 year. Terminal: it can never be
          // walked back. The UI control for this lands in #37; v1 of the struct defaults it to false.
          { name: 'permanentLock', type: 'bool' },
          // #34: the creator's free allocation, in bps of the curve supply, 0 to 500 (5%). Carved out
          // of the curve allocation and vested linearly from graduation (#35). The UI control lands
          // in #37; until then this is always 0, which is the no-pre-mine case.
          { name: 'devAllocationBps', type: 'uint16' },
        ],
      },
    ],
    outputs: [{ name: 'token', type: 'address' }],
  },
  {
    type: 'function',
    name: 'creationFee',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'launchCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'curveOf',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'creatorOf',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'address' }],
  },
  // Immutable. The launchpad names its own V3 factory, so the graduated-pool address is reachable
  // from the launchpad address alone (Stage 2) — one configured address, no second env var to drift.
  {
    type: 'function',
    name: 'v3Factory',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'event',
    name: 'LaunchCreated',
    anonymous: false,
    inputs: [
      { name: 'token', type: 'address', indexed: true },
      { name: 'curve', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'symbol', type: 'string', indexed: false },
      { name: 'metadataURI', type: 'string', indexed: false },
      // The curve params frozen into this launch. Emitted so the UI can show the opening price and
      // the anti-snipe cap without an eth_call — which the pruned RPC refuses on historical blocks.
      { name: 'virtualEthReserve', type: 'uint256', indexed: false },
      { name: 'virtualTokenReserve', type: 'uint256', indexed: false },
      { name: 'curveTokenAllocation', type: 'uint256', indexed: false },
      { name: 'tradeFeeBps', type: 'uint16', indexed: false },
      { name: 'maxBuyPerWallet', type: 'uint256', indexed: false },
      { name: 'antiSnipeThreshold', type: 'uint256', indexed: false },
    ],
  },
] as const
