// Minimal typed ABI for LPLock (#33) - only the members the UI touches.
// Full ABI lives in ../../subgraph/abis/LPLock.json (generated by forge).
//
// The lock's address is read from `LaunchpadFactory.lpLock()`, per ADR-0003.
export const lpLockAbi = [
  // Why a reclaim would be refused right now, or `NoBlocker` (0) if it would succeed.
  //
  // ⚠️ **This is read from the chain and cannot come from the indexer**, which is the whole reason it
  // is here. Two of reclaim's conditions are indexed - the term and whether it has already been
  // reclaimed - but the decisive one is not: `reclaim` requires the POOL to have gone without a swap
  // for `inactivityPeriod`, and that is read live out of the pool's own oracle observation. Nothing
  // in the subgraph knows it, because nothing emits it.
  //
  // ⚠️ The enum is NAMED rather than boolean precisely so this surface can say WHICH condition is
  // outstanding. Mapped to copy in `lib/lock.ts`; the numbering there is this ABI's.
  {
    type: 'function',
    name: 'reclaimBlocker',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint8' }],
  },
  // Seconds since the pool last recorded an observation. Surfaced so an expired lock held open by a
  // live pool can say how quiet the pool actually is, rather than only that it is not quiet enough.
  {
    type: 'function',
    name: 'secondsSincePoolActivity',
    stateMutability: 'view',
    inputs: [{ name: 'pool', type: 'address' }],
    outputs: [{ name: '', type: 'uint32' }],
  },
  // Read live rather than frozen per position, which is exactly why its setter is monotonic
  // (lengthen only). The UI must therefore read it too and never cache a figure across launches.
  {
    type: 'function',
    name: 'inactivityPeriod',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint32' }],
  },
] as const
